name: "Zalo Bot"
description: "Add-on Zalo Bot in Home Assistant"
url: "https://github.com/TriTue2011/has-addons"
version: "2025.10.8"
slug: "zalo_bot"
init: false
map:
  - config:rw
  - data:rw
  - share:rw
host_network: true
ports:
  3000/tcp: null
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
image: "ghcr.io/tritue2011/zalobot-{arch}"

options:
  data_directory: "/config/zalo_bot"
schema:
  data_directory: "str"
